#!/bin/bash

PREFIX=/usr/local
PROGRAM=ethminer_watchdog

mkdir -p $PREFIX/bin
cp $PROGRAM $PREFIX/bin/
cp $PROGRAM.service $PROGRAM.timer /etc/systemd/system/

systemctl enable $PROGRAM.timer
systemctl start $PROGRAM.timer
systemctl status $PROGRAM.timer
